[project]
name = "plantai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrick Almeida", email = "patrickbalmeida@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
plantai = "plantai:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
