[project]
name = "ia-com-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrick Almeida", email = "patrickbalmeida@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ia-com-uv = "ia_com_uv:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
